# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_15.2.app
    - name: Build
      run: swift build -v
    - name: Run tests (macOS)
      run: swift test -v
    - name: Run tests (iOS)
      run: xcodebuild test -scheme CoreColor -destination 'platform=iOS Simulator,name=iPhone 15'
